/* GyanTech Universe public feed + authenticated admin CMS */
const cfg = window.GTU_CONFIG || {};
const configured = cfg.supabaseUrl && cfg.supabaseAnonKey &&
  cfg.supabaseUrl.startsWith("https://") &&
  !cfg.supabaseUrl.includes("PASTE_") && !cfg.supabaseAnonKey.includes("PASTE_");
let supabaseClient = null, allPosts = [], activeFilter = "All", editingImageUrl = "";
const $ = id => document.getElementById(id);
const esc = value => String(value ?? "").replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const dateFmt = value => { if(!value) return ""; const d = new Date(value); return Number.isNaN(+d) ? "" : d.toLocaleDateString("en-IN",{day:"numeric",month:"short",year:"numeric"}); };
function showToast(msg){ const t=$("toast"); t.textContent=msg; t.classList.remove("hidden"); setTimeout(()=>t.classList.add("hidden"),3500); }
function msg(id,text,error=false){const el=$(id);el.textContent=text;el.classList.toggle("error",error);}
function setPanel(id){["loginPanel","dashboard","editor"].forEach(x=>$(x).classList.toggle("hidden",x!==id));}
function iconFor(cat){return ({Scholarship:"🎓",Jharkhand:"🏛️","Government Scheme":"📋",Technology:"💻",Education:"📚",News:"📰"})[cat]||"✦";}
function renderPosts(){
 const q=$("searchInput").value.trim().toLowerCase();
 const visible=allPosts.filter(p=>(activeFilter==="All"||p.category===activeFilter)&&(!q||`${p.title} ${p.summary} ${p.category} ${p.content||""}`.toLowerCase().includes(q)));
 $("postsGrid").innerHTML=visible.map(p=>`<article class="post-card">${p.image_url?`<img class="post-image" src="${esc(p.image_url)}" alt="${esc(p.title)}" loading="lazy">`:`<div class="post-placeholder">${iconFor(p.category)}</div>`}<div class="post-content"><div class="post-meta"><span>${esc(p.category)}</span><span>•</span><span>${dateFmt(p.published_at||p.created_at)}</span></div><h3>${esc(p.title)}</h3><p>${esc(p.summary)}</p><a class="read-more" href="${p.external_url?esc(p.external_url):'#'}" ${p.external_url?'target="_blank" rel="noopener"':'data-read="'+esc(p.id)+'"'}>${p.external_url?'Open related link ↗':'Read full post →'}</a></div></article>`).join("");
 $("emptyState").classList.toggle("hidden",visible.length>0);
 $("postsGrid").classList.toggle("hidden",visible.length===0);
 document.querySelectorAll("[data-read]").forEach(a=>a.addEventListener("click",e=>{e.preventDefault();openArticle(a.dataset.read)}));
}
function openArticle(id){const p=allPosts.find(x=>String(x.id)===String(id));if(!p)return;const w=window.open("","_blank");if(!w){showToast("Article open karne ke liye pop-up allow karein.");return;}w.document.write(`<!doctype html><html lang="hi"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(p.title)}</title><body style="margin:0;background:#071326;color:#edf5ff;font:16px/1.9 Arial,sans-serif"><article style="max-width:780px;margin:40px auto;padding:24px"><a href="https://youtube.com/@gyantechuniverse" style="color:#75e4ff">GyanTech Universe</a><p style="color:#75e4ff;font-size:12px">${esc(p.category)} · ${dateFmt(p.published_at||p.created_at)}</p><h1 style="line-height:1.3">${esc(p.title)}</h1>${p.image_url?`<img src="${esc(p.image_url)}" style="width:100%;max-height:430px;object-fit:cover;border-radius:12px">`:""}<p style="color:#9eafc7">${esc(p.summary)}</p><div style="white-space:pre-wrap">${esc(p.content)}</div>${p.external_url?`<p><a style="color:#75e4ff" href="${esc(p.external_url)}" target="_blank" rel="noopener">Related link ↗</a></p>`:""}<hr style="border-color:#24364c"><small style="color:#8ca0b9">Please verify official government details before applying.</small></article></body></html>`);w.document.close();}
async function loadPublicPosts(){
 if(!configured){allPosts=samplePosts();renderPosts();$("configWarning").classList.remove("hidden");return;}
 try{const {data,error}=await supabaseClient.from("posts").select("*").eq("is_published",true).order("published_at",{ascending:false});if(error)throw error;allPosts=data||[];renderPosts();}
 catch(e){allPosts=samplePosts();renderPosts();console.error(e);showToast("Posts load nahi hue. Supabase setup/policies check karein.");}
}
function samplePosts(){return [
{id:"sample-1",title:"Jharkhand e-Kalyan Scholarship: guide",category:"Scholarship",summary:"Eligibility aur application process samajhne ke liye latest information aur official notice verify karein.",content:"Scholarship ke liye apply karne se pehle eligibility, dates aur required documents official e-Kalyan portal par verify karein.",created_at:new Date().toISOString()},
{id:"sample-2",title:"Jharkhand ration card online services",category:"Jharkhand",summary:"Ration card se judi online services aur process ke liye official portal ki jaankari dekhein.",content:"Ration card ki services ke liye state ke official portal par current process check karein.",created_at:new Date(Date.now()-86400000).toISOString()},
{id:"sample-3",title:"Online forms aur digital services",category:"Technology",summary:"Digital tools aur online services ko step-by-step samajhne ke liye simple guide.",content:"Online form bharte waqt official website ka hi use karein aur OTP/password kisi ke saath share na karein.",created_at:new Date(Date.now()-172800000).toISOString()}
];}
document.querySelectorAll(".filter").forEach(b=>b.addEventListener("click",()=>{activeFilter=b.dataset.filter;document.querySelectorAll(".filter").forEach(x=>x.classList.toggle("active",x===b));renderPosts();}));
document.querySelectorAll("[data-filter]").forEach(a=>{if(a.tagName==="A")a.addEventListener("click",()=>{activeFilter=a.dataset.filter;document.querySelectorAll(".filter").forEach(x=>x.classList.toggle("active",x.dataset.filter===activeFilter));renderPosts();});});
$("searchInput").addEventListener("input",renderPosts);$("year").textContent=new Date().getFullYear();
$("hamburger").addEventListener("click",()=>$("nav").classList.toggle("open"));$("nav").querySelectorAll("a").forEach(a=>a.addEventListener("click",()=>$("nav").classList.remove("open")));
$("adminOpen").addEventListener("click",()=>{$("adminModal").classList.remove("hidden");if(!configured){$("configWarning").classList.remove("hidden");}else $("configWarning").classList.add("hidden");});
$("closeAdmin").addEventListener("click",()=>$("adminModal").classList.add("hidden"));$("adminModal").addEventListener("click",e=>{if(e.target===$("adminModal"))$("adminModal").classList.add("hidden");});
$("loginBtn").addEventListener("click",async()=>{if(!configured){msg("adminMessage","Pehle config.js mein Supabase URL aur public anon/publishable key set karein.",true);$("configWarning").classList.remove("hidden");return;}const email=$("adminEmail").value.trim(),password=$("adminPassword").value;if(!email||!password){msg("adminMessage","Email aur password dono bharein.",true);return;}const {error}=await supabaseClient.auth.signInWithPassword({email,password});if(error){msg("adminMessage",error.message,true);return;}msg("adminMessage","Login successful.");setPanel("dashboard");await loadAdminPosts();});
$("logoutBtn").addEventListener("click",async()=>{await supabaseClient?.auth.signOut();setPanel("loginPanel");$("adminPassword").value="";});
$("newPostBtn").addEventListener("click",()=>openEditor());$("cancelEditor").addEventListener("click",()=>setPanel("dashboard"));$("cancelEditor2").addEventListener("click",()=>setPanel("dashboard"));
function openEditor(p=null){$("postForm").reset();$("postId").value=p?.id||"";$("postTitle").value=p?.title||"";$("postCategory").value=p?.category||"Scholarship";$("postSummary").value=p?.summary||"";$("postContent").value=p?.content||"";$("postLink").value=p?.external_url||"";editingImageUrl=p?.image_url||"";$("editorHeading").textContent=p?"Edit post":"Create new post";$("publishBtn").textContent=p?"Save changes":"Publish Post";msg("editorMessage","");setPanel("editor");}
async function loadAdminPosts(){if(!supabaseClient)return;const {data,error}=await supabaseClient.from("posts").select("*").order("created_at",{ascending:false});if(error){msg("adminMessage",error.message,true);return;}const wrap=$("adminPosts");if(!data?.length){wrap.innerHTML='<p class="small-note">Abhi koi post nahi hai. “New Post” se pehla post banayein.</p>';return;}wrap.innerHTML=data.map(p=>`<div class="admin-post-row"><div class="row-text"><b>${esc(p.title)}</b><small>${esc(p.category)} · ${p.is_published?"Published":"Draft"}</small></div><button class="mini-button" data-edit="${esc(p.id)}">Edit</button><button class="mini-button danger" data-delete="${esc(p.id)}">Delete</button></div>`).join("");wrap.querySelectorAll("[data-edit]").forEach(b=>b.addEventListener("click",()=>openEditor(data.find(p=>String(p.id)===b.dataset.edit))));wrap.querySelectorAll("[data-delete]").forEach(b=>b.addEventListener("click",()=>deletePost(b.dataset.delete)));}
async function deletePost(id){if(!confirm("Is post ko permanently delete karna hai?"))return;const {error}=await supabaseClient.from("posts").delete().eq("id",id);if(error){msg("adminMessage",error.message,true);return;}showToast("Post delete ho gaya.");await loadAdminPosts();await loadPublicPosts();}
$("postForm").addEventListener("submit",async e=>{e.preventDefault();if(!supabaseClient)return;const btn=$("publishBtn");btn.disabled=true;btn.textContent="Saving…";try{let imageUrl=editingImageUrl;const file=$("postImage").files[0];if(file){if(file.size>5*1024*1024)throw new Error("Image 5 MB se chhoti honi chahiye.");if(!["image/jpeg","image/png","image/webp"].includes(file.type))throw new Error("JPG, PNG ya WebP image use karein.");const ext=file.name.split(".").pop().toLowerCase();const path=`${crypto.randomUUID()}.${ext}`;const {error:upErr}=await supabaseClient.storage.from("post-images").upload(path,file,{upsert:false,contentType:file.type});if(upErr)throw upErr;const {data}=supabaseClient.storage.from("post-images").getPublicUrl(path);imageUrl=data.publicUrl;}
const id=$("postId").value;const payload={title:$("postTitle").value.trim(),category:$("postCategory").value,summary:$("postSummary").value.trim(),content:$("postContent").value.trim(),external_url:$("postLink").value.trim()||null,image_url:imageUrl||null,is_published:true,published_at:new Date().toISOString()};let result;if(id)result=await supabaseClient.from("posts").update(payload).eq("id",id);else result=await supabaseClient.from("posts").insert(payload);if(result.error)throw result.error;showToast(id?"Post updated!":"Post published!");setPanel("dashboard");await loadAdminPosts();await loadPublicPosts();}
catch(err){msg("editorMessage",err.message||"Save nahi ho paya.",true);}finally{btn.disabled=false;btn.textContent=$("postId").value?"Save changes":"Publish Post";}});
async function init(){if(!configured){allPosts=samplePosts();renderPosts();$("configWarning").classList.remove("hidden");return;}try{const {createClient}=await import("https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm");supabaseClient=createClient(cfg.supabaseUrl,cfg.supabaseAnonKey);const {data:{session}}=await supabaseClient.auth.getSession();if(session){setPanel("dashboard");await loadAdminPosts();}await loadPublicPosts();}catch(e){console.error(e);allPosts=samplePosts();renderPosts();showToast("Connection setup check karein.");}}
init();
