-- GyanTech Universe CMS: run this SQL in Supabase SQL Editor.
-- Public visitors can read only published posts. Only authenticated users can manage posts.
create table if not exists public.posts (
  id bigint generated by default as identity primary key,
  title text not null,
  category text not null default 'News',
  summary text not null,
  content text not null,
  image_url text,
  external_url text,
  is_published boolean not null default true,
  created_at timestamptz not null default now(),
  published_at timestamptz
);

alter table public.posts enable row level security;

drop policy if exists "Anyone can read published posts" on public.posts;
create policy "Anyone can read published posts"
on public.posts for select
to anon, authenticated
using (is_published = true or auth.uid() is not null);

drop policy if exists "Authenticated admins can insert posts" on public.posts;
create policy "Authenticated admins can insert posts"
on public.posts for insert to authenticated
with check (auth.uid() is not null);

drop policy if exists "Authenticated admins can update posts" on public.posts;
create policy "Authenticated admins can update posts"
on public.posts for update to authenticated
using (auth.uid() is not null)
with check (auth.uid() is not null);

drop policy if exists "Authenticated admins can delete posts" on public.posts;
create policy "Authenticated admins can delete posts"
on public.posts for delete to authenticated
using (auth.uid() is not null);

-- Create a Storage bucket named post-images in the Supabase dashboard.
-- For production, restrict admin writes to a dedicated admin role/user rather than all authenticated users.
-- Storage policies (simple authenticated-write starter; harden if other users will ever be allowed to sign up):
drop policy if exists "Public can view post images" on storage.objects;
create policy "Public can view post images" on storage.objects
for select to anon, authenticated
using (bucket_id = 'post-images');

drop policy if exists "Authenticated users can upload post images" on storage.objects;
create policy "Authenticated users can upload post images" on storage.objects
for insert to authenticated
with check (bucket_id = 'post-images' and auth.uid() is not null);

drop policy if exists "Authenticated users can update post images" on storage.objects;
create policy "Authenticated users can update post images" on storage.objects
for update to authenticated
using (bucket_id = 'post-images' and auth.uid() is not null)
with check (bucket_id = 'post-images' and auth.uid() is not null);

drop policy if exists "Authenticated users can delete post images" on storage.objects;
create policy "Authenticated users can delete post images" on storage.objects
for delete to authenticated
using (bucket_id = 'post-images' and auth.uid() is not null);
